theme: jekyll-theme-minimal
title: Kelian Dascher-Cousineau
description:

  <head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-1FL4E7ECPD"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-1FL4E7ECPD');
    </script>
  </head>

  <div>
    <i class="material-icons" style="vertical-align:middle">pages</i> <a href="./Blog">Blog</a>
  </div>

  <div>
    <i class="material-icons" style="vertical-align:middle">email</i> kdascher@berkeley.edu
  </div>

  <div>
    <i class="material-icons" style="vertical-align:middle">school</i> <a href="https://scholar.google.ca/citations?hl=en&user=XsIHgIsAAAAJ">Google Scholar Profile</a>
  </div>

  <div>
    <i class="material-icons" style="vertical-align:middle">bookmark</i> <a href="assets/docs/Kelian Dascher-Cousineau - Resume 2023.pdf">Resume</a>
  </div>

plugins:
  - jekyll-gist
  - jekyll-twitter-plugin
  - jekyll-seo-tag
